### ISSUE TITLE
openSUSE 13.2 integration

### ISSUE THREAD

**Issue by SandraWeddig** [webyast/webyast#103]
Hi!

I love your product and begin to use openSUSE 13.2. 
When will webyast be avaible at this version?

Thx, Sandra

**Comment by xarinatan** [comment]
Any new plans for releasing Webyast? I wanted to make a simple router distro with suse studio, but with Webyast being out of the picture I guess that's a no-go. Really sad, it looked kinda neat, like webmin but for opensuse (which I personally prefer over debian).

**Comment by dmacvicar** [comment]
@xarinatan have you tried if http://cockpit-project.org works? I think someone packaged it on the build service: http://software.opensuse.org/package/cockpit

**Comment by xarinatan** [comment]
@dmacvicar Looks interesting, though no word on whether it manages firewalld or just iptables, let alone other packages like DHCP, DNS, etc.. Will definitely give it a try though!

**Comment by xarinatan** [comment]
@dmacvicar Cockpit seems like a very limited interface, it doesn't even have iptables support, it seems mostly oriented towards starting/stopping docker containers, viewing system logs, and starting/stopping systemd services, managing users, and viewing some pretty graphs about the system load. 

I'm sure it's alright for its intended purpose, but I'm looking for something that has a proper DNS management interface, can handle things like DHCP configuration, add/remove port mappings and masquerading, and perhaps some webmin-esque editing of configuration files for random assorted packages. 

It seems strange how scarce these interfaces are, especially how relatively easy it should be to make them; Just a config parser, bootstrap.css, some graphing JS library, and a backend that holds it together and serves the pages. Might be a 2 week project for a bunch of students. Usually people tell me to 'lrn2CLI', but I'm perfectly capable of CLI management, it's just not as convenient and fast. Plus it would mean people with no CLI access could help me manage servers, what if I just want to let someone else add port mappings? "What's an SSH, how do I shot this in web?" 

Webyast would seem ideal, as it integrates with the already extensive yast backend, and would thus automatically be able to manage tons of different packages, but I guess the higher ups have decided the priorities are elsewhere. A shame though! It would've been so perfect if I could just click together a router OS or some webmanaged network appliance alike in suse studio ;) but alas, I'm sure they have their reasons :) I'll just continue my search.
